### PR TITLE
 Updated to Swift 4/Xcode 10

### PR DESCRIPTION
**Pull request by vitallica**
- Updated Carthage dependencies.
- Fixed syntax errors.

### CODE REVIEW

**Comment by vitallica** [comment]
@yoichitgy The CI build is failing because it's trying to build with Xcode 8. This PR requires Xcode 10. Is it possible to update the CI settings?

**Comment by jakubvano** [comment]
Thanks for the PR 👍 
You can update the Xcode version in the [.travis.yml](https://github.com/Swinject/SwinjectPropertyLoader/blob/master/.travis.yml) - it should be enough to make CI pass.

**Comment by vitallica** [comment]
@jakubvano Thanks for pointing me in the right direction!

**Comment by vitallica** [comment]
@jakubvano Can you please review this PR? CI is now passing.

**Comment by jakubvano** [comment]
👍 looks OK

**Pull request merged**
