### PR TITLE
Substring changes

### PR DESCRIPTION
**Pull request by edpelesh**
Fixed deprecation warnings that blocked Carthage to finish updating.

### CODE REVIEW

**Comment by kreeger** [comment]
This is hanging me up, too. I'd love to see this merged in.

**Comment by yoichitgy** [comment]
Thanks @edpelesh for the PR and sorry that I took time so long to respond. We need to fix the CI failure to merge this PR.

**Comment by yoichitgy** [comment]
I'll try checking the CI failure, but it's really appreciated if you investigate the problem.

**Comment by edpelesh** [comment]
I've added a compilation conditional check. Please, check this solution. I doesn't look very clean, but at least it does what it needs.

**Comment by serebryakov7** [comment]
So, can it be merged?

**Comment by VEnis** [comment]
+1 for merge

**Comment by yoichitgy** [comment]
Thank you for making the PR😃 and sorry for taking too long time to response.

It looks the similar change is covered by PR #20. Let me close this PR🙏

**Pull request closed without merging**
